Import('env')

# ---------------------------------------------------------------

name = 'dso_switch_float_map'
target = 'SwitchFloatMap.so'
cc_source = ['SwitchFloatMap.cc']
ispc_source = ['SwitchFloatMap.ispc']
json_source = ['SwitchFloatMap.json']
components = [
    'render_util',
    'rendering_shading',
    'shading_ispc',
    'scene_rdl2',
]

# ---------------------------------------------------------------

()
env.DWAUseComponents(components)
dso = env.DWAIspcDso(env.File(target), cc_source, ispc_source, json_source)
env.DWAInstallIspcDso(dso)
env.DWAComponent(name, COMPONENTS=components)
