Import('env')

target = 'ConstantColorMap.so'
cc_source = ['ConstantColorMap.cc']
ispc_source = ['ConstantColorMap.ispc']
json_source = ['ConstantColorMap.json']
components = [
    'shading_ispc',
    'scene_rdl2'
]

# ---------------------------------------------------------------

env.DWAUseComponents(components)
dso = env.DWAIspcDso(env.File(target), cc_source, ispc_source, json_source)
env.DWAInstallIspcDso(dso)
