Import('env')

# ---------------------------------------------------------------

target = 'ProjectTriplanarMap_v2.so'
cc_source = ['ProjectTriplanarMap_v2.cc']
ispc_source = ['ProjectTriplanarMap_v2.ispc']
json_source = ['ProjectTriplanarMap_v2.json']
components = [
    'shading_ispc',
    'rendering_shading',
    'scene_rdl2',
    'map_projection',
    'map_primvar'
]

# ---------------------------------------------------------------

()
env.DWAUseComponents(components)
dso = env.DWAIspcDso(env.File(target), cc_source, ispc_source, json_source)
env.DWAInstallIspcDso(dso)
