Import('env')

# ---------------------------------------------------------------

target = 'DistortNormalMap.so'
cc_source = ['DistortNormalMap.cc']
ispc_source = ['DistortNormalMap.ispc']
json_source = ['DistortNormalMap.json']
components = [
    'common_noise',
    'common_interpolation',
    'map_primvar',
    'shading_ispc',
    'rendering_shading',
    'scene_rdl2',
]

# ---------------------------------------------------------------

()
env.DWAUseComponents(components)
dso = env.DWAIspcDso(env.File(target), cc_source, ispc_source, json_source)
env.DWAInstallIspcDso(dso)
