Import('env')

# ---------------------------------------------------------------

target = 'NoiseMap_v2.so'
cc_source = ['NoiseMap_v2.cc']
ispc_source = ['NoiseMap_v2.ispc']
json_source = ['NoiseMap_v2.json']
components = [
    'common_noise',
    'common_interpolation',
    'map_primvar',
    'rendering_geom',
    'rendering_shading',
    'render_util',
    'scene_rdl2',
    'shading_ispc'
]

()
env.DWAUseComponents(components)
dso = env.DWAIspcDso(env.File(target), cc_source, ispc_source, json_source)
env.DWAInstallIspcDso(dso)

