import os
Import('env')

# ---------------------------------------------------------------

name = 'dso_toondisplayfilter'
target = 'ToonDisplayFilter.so'
cc_source = ['ToonDisplayFilter.cc']
ispc_source = ['ToonDisplayFilter.ispc']
json_source = ['ToonDisplayFilter.json']
components = [
    'rendering_displayfilter',
    'scene_rdl2'
]

# ---------------------------------------------------------------
()
env.DWAUseComponents(components)
dso = env.DWAIspcDso(env.File(target), cc_source, ispc_source, json_source)
env.DWAInstallIspcDso(dso)
