Import('env')


# ---------------------------------------------------------------

target = 'ColorCorrectHueShiftMap.so'
cc_source = ['ColorCorrectHueShiftMap.cc']
ispc_source = ['ColorCorrectHueShiftMap.ispc']
json_source = ['ColorCorrectHueShiftMap.json']
components = [
    'shading_ispc',
    'scene_rdl2'
]

# ---------------------------------------------------------------

()
env.DWAUseComponents(components)
dso = env.DWAIspcDso(env.File(target), cc_source, ispc_source, json_source)
env.DWAInstallIspcDso(dso)
