Import('env')

# ---------------------------------------------------------------

target = 'RampMap.so'
cc_source = ['RampMap.cc']
ispc_source = ['RampMap.ispc']
json_source = ['RampMap.json']
components = [
    'render_util',
    'rendering_shading',
    'shading_ispc',
    'scene_rdl2',
]

# ---------------------------------------------------------------

# TODO: re-write code to avoid performance warnings
env.AppendUnique(ISPCFLAGS = ['--wno-perf'])

# env.DWAForceWarningAsError()
env.DWAUseComponents(components)
dso = env.DWAIspcDso(env.File(target), cc_source, ispc_source, json_source)
env.DWAInstallIspcDso(dso)

