Import('env')

# ---------------------------------------------------------------

name = 'dso_toon_map'
target = 'ToonMap.so'
cc_source = ['ToonMap.cc']
ispc_source = ['ToonMap.ispc']
json_source = ['ToonMap.json']
components = [
    'shading_ispc',
    'scene_rdl2',
    'rendering_shading',
]

# ---------------------------------------------------------------

env.DWAForceWarningAsError()
env.DWAUseComponents(components)
dso = env.DWAIspcDso(env.File(target), cc_source, ispc_source, json_source)
env.DWAInstallIspcDso(dso)
env.DWAComponent(name, COMPONENTS=components)
