Import('env')

# ---------------------------------------------------------------

name = 'dso_op_map'
target = 'OpMap.so'
cc_source = ['OpMap.cc']
ispc_source = ['OpMap.ispc']
json_source = ['OpMap.json']
components = [
    'render_util',
    'rendering_shading',
    'shading_ispc',
    'scene_rdl2',
]

# ---------------------------------------------------------------

env.DWAUseComponents(components)

# TODO: re-write code to avoid performance warnings
env.AppendUnique(ISPCFLAGS = ['--wno-perf'])

dso = env.DWAIspcDso(env.File(target), cc_source, ispc_source, json_source)
env.DWAInstallIspcDso(dso)
env.DWAComponent(name, COMPONENTS=components)
