import os
Import('env')

# ---------------------------------------------------------------

name = 'dso_overdisplayfilter'
target = 'OverDisplayFilter.so'
cc_source = ['OverDisplayFilter.cc']
ispc_source = ['OverDisplayFilter.ispc']
json_source = ['OverDisplayFilter.json']
components = [
    'rendering_displayfilter',
    'scene_rdl2'
]

# ---------------------------------------------------------------
()
env.DWAUseComponents(components)
dso = env.DWAIspcDso(env.File(target), cc_source, ispc_source, json_source)
env.DWAInstallIspcDso(dso)
