import os
Import('env')

# ---------------------------------------------------------------

name = 'dso_dofdisplayfilter'
target = 'DofDisplayFilter.so'
cc_source = ['DofDisplayFilter.cc']
ispc_source = ['DofDisplayFilter.ispc']
json_source = ['DofDisplayFilter.json']
components = [
    'rendering_displayfilter',
    'scene_rdl2'
]

# ---------------------------------------------------------------
()
env.DWAUseComponents(components)
dso = env.DWAIspcDso(env.File(target), cc_source, ispc_source, json_source)
env.DWAInstallIspcDso(dso)
