Import('env')

# ---------------------------------------------------------------

name = 'dso_random_map'
target = 'RandomMap.so'
cc_source = ['RandomMap.cc']
ispc_source = ['RandomMap.ispc']
json_source = ['RandomMap.json']
components = [
    'rendering_shading',
    'shading_ispc',
    'scene_rdl2'
]

# ---------------------------------------------------------------

env.DWAUseComponents(components)

# TODO: re-write code to avoid performance warnings
env.AppendUnique(ISPCFLAGS = ['--wno-perf'])

dso = env.DWAIspcDso(env.File(target), cc_source, ispc_source, json_source)
env.DWAInstallIspcDso(dso)
env.DWAComponent(name, COMPONENTS=components)
