Import('env')

# ---------------------------------------------------------------

target = 'ColorCorrectLegacyMap.so'
cc_source = ['ColorCorrectLegacyMap.cc']
ispc_source = ['ColorCorrectLegacyMap.ispc']
json_source = ['ColorCorrectLegacyMap.json']
components = [
    'shading_ispc',
    'scene_rdl2'
]

# ---------------------------------------------------------------

env.DWAForceWarningAsError()
env.DWAUseComponents(components)
dso = env.DWAIspcDso(env.File(target), cc_source, ispc_source, json_source)
env.DWAInstallIspcDso(dso)
