import os
Import('env')

# ---------------------------------------------------------------

name = 'dso_tangentspacedisplayfilter'
target = 'TangentSpaceDisplayFilter.so'
cc_source = ['TangentSpaceDisplayFilter.cc']
ispc_source = ['TangentSpaceDisplayFilter.ispc']
json_source = ['TangentSpaceDisplayFilter.json']
components = [
    'rendering_displayfilter',
    'scene_rdl2'
]

# ---------------------------------------------------------------
()
env.DWAUseComponents(components)
dso = env.DWAIspcDso(env.File(target), cc_source, ispc_source, json_source)
env.DWAInstallIspcDso(dso)
