Import('env')

# ---------------------------------------------------------------

# rename name/target/sources to proper dso/file name before installing dso
name = 'dso_templategeometry'
target = 'TemplateGeometry.so'
sources = ['TemplateGeometry.cc']
components = [
    'render_util',
    'rendering_geom',
    'scene_rdl2'
]

# ---------------------------------------------------------------

env.DWAForceWarningAsError()
env.DWAUseComponents(components)
dso = env.DWARdl2Dso(env.File(target), sources)
# template dso not installed, uncomment to install
#env.DWAInstallRdl2Dso(dso)

