Import('env')

# ---------------------------------------------------------------

name = 'dso_hairmap'
target = 'HairMap.so'
cc_source = ['HairMap.cc']
ispc_source = ['HairMap.ispc']
json_source = ['HairMap.json']
components = [
    'render_util',
    'rendering_shading',
    'shading_ispc',
    'texturing_sampler',
    'scene_rdl2'
]

# ---------------------------------------------------------------

()
env.DWAUseComponents(components)
dso = env.DWAIspcDso(env.File(target), cc_source, ispc_source, json_source)
env.DWAInstallIspcDso(dso)
env.DWAComponent(name, COMPONENTS=components)
