Import('env')

target = 'ConstantScalarMap.so'
cc_source = ['ConstantScalarMap.cc']
ispc_source = ['ConstantScalarMap.ispc']
json_source = ['ConstantScalarMap.json']
components = [
    'shading_ispc',
    'scene_rdl2'
]

# ---------------------------------------------------------------

env.DWAUseComponents(components)
dso = env.DWAIspcDso(env.File(target), cc_source, ispc_source, json_source)
env.DWAInstallIspcDso(dso)
