Import('env')

# ---------------------------------------------------------------

name = 'dso_multichanneltofloatmap'
target = 'MultiChannelToFloatMap.so'
cc_source = ['MultiChannelToFloatMap.cc']
ispc_source = ['MultiChannelToFloatMap.ispc']
json_source = ['MultiChannelToFloatMap.json']
components = [
    'common_math',
    'rendering_shading',
    'shading_ispc',
    'scene_rdl2'
]

# ---------------------------------------------------------------
()
env.DWAUseComponents(components)
dso = env.DWAIspcDso(env.File(target), cc_source, ispc_source, json_source)
env.DWAInstallIspcDso(dso)
env.DWAComponent(name, COMPONENTS=components)
