Import('env')

# ---------------------------------------------------------------

name = 'dso_boxgeometry'
target = 'BoxGeometry.so'
sources = ['BoxGeometry.cc']
components = [
    'render_util',
    'rendering_geom',
    'rendering_shading',
    'scene_rdl2',
]

# ---------------------------------------------------------------

env.DWAForceWarningAsError()
env.DWAUseComponents(components)
dso = env.DWARdl2Dso(env.File(target), sources)
env.DWAInstallRdl2Dso(dso)

