import os
Import('env')

# ---------------------------------------------------------------

name = 'dso_rgbtohsvdisplayfilter'
target = 'RgbToHsvDisplayFilter.so'
cc_source = ['RgbToHsvDisplayFilter.cc']
ispc_source = ['RgbToHsvDisplayFilter.ispc']
json_source = ['RgbToHsvDisplayFilter.json']
components = [
    'rendering_displayfilter',
    'scene_rdl2'
]

# ---------------------------------------------------------------
()
env.DWAUseComponents(components)
dso = env.DWAIspcDso(env.File(target), cc_source, ispc_source, json_source)
env.DWAInstallIspcDso(dso)
