Import('env')
# ---------------------------------------------------------------
target = 'TemplateMap.so'
cc_source = ['TemplateMap.cc']
ispc_source = ['TemplateMap.ispc']
json_source = ['TemplateMap.json']

components = [
    'shading_ispc',
    'scene_rdl2'
]
# ---------------------------------------------------------------
env.DWAForceWarningAsError()
env.DWAUseComponents(components)
env.AppendUnique(CPPPATH=[env.Dir('.')])
dso = env.DWAIspcDso(env.File(target), cc_source, ispc_source, json_source)
# template dso not installed, uncomment to install
# env.DWAInstallIspcDso(dso)
