import os
Import('env')

# ---------------------------------------------------------------

name = 'dso_remapcorrectdisplayfilter'
target = 'RemapDisplayFilter.so'
cc_source = ['RemapDisplayFilter.cc']
ispc_source = ['RemapDisplayFilter.ispc']
json_source = ['RemapDisplayFilter.json']
components = [
    'rendering_displayfilter',
    'scene_rdl2'
]

# ---------------------------------------------------------------
()
env.DWAUseComponents(components)
dso = env.DWAIspcDso(env.File(target), cc_source, ispc_source, json_source)
env.DWAInstallIspcDso(dso)
