import os
Import('env')

# ---------------------------------------------------------------

name = 'dso_opdisplayfilter'
target = 'OpDisplayFilter.so'
cc_source = ['OpDisplayFilter.cc']
ispc_source = ['OpDisplayFilter.ispc']
json_source = ['OpDisplayFilter.json']
components = [
    'rendering_displayfilter',
    'scene_rdl2'
]

# ---------------------------------------------------------------
()
env.DWAUseComponents(components)
dso = env.DWAIspcDso(env.File(target), cc_source, ispc_source, json_source)
env.DWAInstallIspcDso(dso)
