import os
Import('env')

name = 'dso_dwamixmaterial'
target = 'DwaMixMaterial.so'
cc_source = ['DwaMixMaterial.cc']
ispc_source = ['DwaMixMaterial.ispc']
json_source = ['DwaMixMaterial.json']
components = [
    'rendering_shading',
    'shading_ispc',
    'material_dwabase',
    'scene_rdl2'
]

# --------------------------------------------------------------
env.DWAUseComponents(components)
dso = env.DWAIspcDso(env.File(target), cc_source, ispc_source, json_source)

env.DWAInstallIspcDso(dso)

baseDso = env.DWAComponent(
    name,
    COMPONENTS=components
)
env.AlwaysBuild(baseDso)

