Import('env')
from os import path

modName = path.basename(path.abspath('..'))
libName = path.basename(path.abspath('.'))
name    = modName + "_" + libName

# --------------------------------------------------------------------------

# for this option to take affect, it must be added *before* we add the ispc sources.
env.AppendUnique(ISPCFLAGS = ['--opt=force-aligned-memory'])

components  = ['scene_rdl2', 'rendering_shading', 'shading_ispc']
env.DWAUseComponents(components)

sources, headers = env.IspcShared(['ispc/Projection.ispc', 'ispc/TriplanarTexture.ispc' ])
sources     += env.DWAGlob('*.cc')
incdir = [
    env.Dir('../../../..').srcnode(),
    env.Dir('../../').srcnode(),
    env.Dir('../projection').abspath,
    env.Dir('../projection/ispc').abspath,
    env.Dir('.'),
    env.Dir('ispc')
]

# --------------------------------------------------------------------------

env.Append(CPPPATH=incdir)
lib = env.DWASharedLibrary(name, sources)
target = env.DWAInstallLib(lib)
env.DWAInstallSConscriptStub(name, LIBS=target,
                             CPPPATH=[env.Dir('$INSTALL_DIR/include')],
                             COMPONENTS=components)
env.DWAComponent(name, LIBS=[target], CPPPATH=incdir, COMPONENTS=components)
env.DWALinkValidate(name)
