Import('env')

# ---------------------------------------------------------------

name = 'dso_hairtoonmaterial'
target = 'HairToonMaterial.so'
cc_source = ['HairToonMaterial.cc']
ispc_source = ['HairToonMaterial.ispc']
json_source = ['HairToonMaterial.json']
components = [
    'render_util',
    'shading_ispc',
    'material_dwabase',
    'scene_rdl2'
]

# ---------------------------------------------------------------

env.DWAUseComponents(components)
dso = env.DWAIspcDso(env.File(target), cc_source, ispc_source, json_source)
env.DWAInstallIspcDso(dso)
env.DWAComponent(name, COMPONENTS=components)
