Import('env')

# ---------------------------------------------------------------

name = 'dso_uvtransformmap'
target = 'UVTransformMap.so'
cc_source = ['UVTransformMap.cc']
ispc_source = ['UVTransformMap.ispc']
json_source = ['UVTransformMap.json']
components = [
    'rendering_shading',
    'shading_ispc',
    'scene_rdl2',
]

# ---------------------------------------------------------------
()
env.DWAUseComponents(components)
dso = env.DWAIspcDso(env.File(target), cc_source, ispc_source, json_source)
env.DWAInstallIspcDso(dso)
env.DWAComponent(name, COMPONENTS=components)
