import os
Import('env')

# ---------------------------------------------------------------

name = 'dso_constantdisplayfilter'
target = 'ConstantDisplayFilter.so'
cc_source = ['ConstantDisplayFilter.cc']
ispc_source = ['ConstantDisplayFilter.ispc']
json_source = ['ConstantDisplayFilter.json']
components = [
    'rendering_displayfilter',
    'scene_rdl2'
]

# ---------------------------------------------------------------
()
env.DWAUseComponents(components)
dso = env.DWAIspcDso(env.File(target), cc_source, ispc_source, json_source)
env.DWAInstallIspcDso(dso)
