Import('env')

# ---------------------------------------------------------------

name = 'dso_hairdiffusematerial'
target = 'HairDiffuseMaterial.so'
cc_source = ['HairDiffuseMaterial.cc']
ispc_source = ['HairDiffuseMaterial.ispc']
json_source = ['HairDiffuseMaterial.json']
components = [
    'render_util',
    'rendering_pbr',
    'shading_ispc',
    'material_dwabase',
    'scene_rdl2'
]

# ---------------------------------------------------------------

()
env.DWAUseComponents(components)
dso = env.DWAIspcDso(env.File(target), cc_source, ispc_source, json_source)
env.DWAInstallIspcDso(dso)
env.DWAComponent(name, COMPONENTS=components)
