Import('env')

# ---------------------------------------------------------------

name = 'dso_clamp_map'
target = 'ClampMap.so'
cc_source = ['ClampMap.cc']
ispc_source = ['ClampMap.ispc']
json_source = ['ClampMap.json']
components = [
    'rendering_shading',
    'shading_ispc',
    'scene_rdl2'
]

# ---------------------------------------------------------------

env.DWAUseComponents(components)
dso = env.DWAIspcDso(env.File(target), cc_source, ispc_source, json_source)
env.DWAInstallIspcDso(dso)
env.DWAComponent(name, COMPONENTS=components)
