import os
Import('env')

# ---------------------------------------------------------------

name = 'dso_clampdisplayfilter'
target = 'ClampDisplayFilter.so'
cc_source = ['ClampDisplayFilter.cc']
ispc_source = ['ClampDisplayFilter.ispc']
json_source = ['ClampDisplayFilter.json']
components = [
    'rendering_displayfilter',
    'scene_rdl2'
]

# ---------------------------------------------------------------
()
env.DWAUseComponents(components)
dso = env.DWAIspcDso(env.File(target), cc_source, ispc_source, json_source)
env.DWAInstallIspcDso(dso)
