Import('env')

# ---------------------------------------------------------------

name = 'dso_switchdisplacement'
target = 'SwitchDisplacement.so'
cc_source = ['SwitchDisplacement.cc']
ispc_source = ['SwitchDisplacement.ispc']
json_source = ['SwitchDisplacement.json']
components = [
    'rendering_shading',
    'scene_rdl2',
    'shading_ispc'
]

# ---------------------------------------------------------------

env.DWAUseComponents(components)
dso = env.DWAIspcDso(env.File(target), cc_source, ispc_source, json_source)
env.DWAInstallIspcDso(dso)
env.DWAComponent(name, COMPONENTS=components)
