import os
Import('env')

# ---------------------------------------------------------------

name = 'dso_halftonedisplayfilter'
target = 'HalftoneDisplayFilter.so'
cc_source = ['HalftoneDisplayFilter.cc']
ispc_source = ['HalftoneDisplayFilter.ispc']
json_source = ['HalftoneDisplayFilter.json']
components = [
    'rendering_displayfilter',
    'scene_rdl2'
]

# ---------------------------------------------------------------
()
env.DWAUseComponents(components)
dso = env.DWAIspcDso(env.File(target), cc_source, ispc_source, json_source)
env.DWAInstallIspcDso(dso)
