import os
Import('env')

# ---------------------------------------------------------------

name = 'dso_rgbtofloatdisplayfilter'
target = 'RgbToFloatDisplayFilter.so'
cc_source = ['RgbToFloatDisplayFilter.cc']
ispc_source = ['RgbToFloatDisplayFilter.ispc']
json_source = ['RgbToFloatDisplayFilter.json']
components = [
    'rendering_displayfilter',
    'scene_rdl2'
]

# ---------------------------------------------------------------
()
env.DWAUseComponents(components)
dso = env.DWAIspcDso(env.File(target), cc_source, ispc_source, json_source)
env.DWAInstallIspcDso(dso)
