import os
Import('env')

name = 'dso_dwavelvetmaterial_v2'
target = 'DwaVelvetMaterial_v2.so'
cc_source = ['DwaVelvetMaterial_v2.cc']
ispc_source = ['DwaVelvetMaterial_v2.ispc']
json_source = ['DwaVelvetMaterial_v2.json']
components = [
    'render_util',
    'shading_ispc',
    'material_dwabase',
    'scene_rdl2'
]

# ---------------------------------------------------------------
env.DWAUseComponents(components)
dso = env.DWAIspcDso(env.File(target), cc_source, ispc_source, json_source)

env.DWAInstallIspcDso(dso)

baseDso = env.DWAComponent(
    name,
    COMPONENTS=components
)
env.AlwaysBuild(baseDso)

