Import('env')

# ---------------------------------------------------------------

target = 'ProjectCameraMap.so'
cc_source = ['ProjectCameraMap.cc']
ispc_source = ['ProjectCameraMap.ispc']
json_source = ['ProjectCameraMap.json']
components = [
    'map_primvar',
    'map_projection',
    'rendering_shading',
    'scene_rdl2',
    'shading_ispc'
]

# ---------------------------------------------------------------

()
env.DWAUseComponents(components)
dso = env.DWAIspcDso(env.File(target), cc_source, ispc_source, json_source)
env.DWAInstallIspcDso(dso)
