Import('env')
from os import path

env.AppendUnique(ISPCFLAGS=['--wno-perf', '--woff'])

modName = path.basename(path.abspath('..'))
libName = path.basename(path.abspath('.'))
# --------------------------------------------------------------------------
name = modName + '_' + libName
sources = []

sources += [
            'PrimitiveUserData.cc',
            ]

incdir = [str(env.Dir('../..').srcnode()), env['BUILD_DIR'] + '/autogenerate']

public_headers = [
                  'PrimitiveUserData.h',
                 ]
env.DWAInstallInclude(public_headers, 'moonshine/geometry/data')

components = [
            'scene_rdl2',
            'rendering_bvh_shading',
            'rendering_geom',
            'rendering_shading',
            ]

env.DWAForceWarningAsError()

# --------------------------------------------------------------------------
# Have to add option '-diag-disable=remark' to work around a compiler bug
# ICC 15 complains about OsdCCSubdMeshAdaptive.cc line 62 for function AddWithWeight
# simd loop has only one iteration
# Which I think is a compiler bug since nElement equals to 2, 4, or 8
# Will follow up with ICC compiler team
if 'icc' in env['CC']:
    ccflags = ['-diag-disable=remark']
else:
    ccflags = []
env.Prepend (CPPPATH=incdir, CCFLAGS=ccflags)

env.DWAUseComponents(components)
lib = env.DWASharedLibrary(name, sources)
target = env.DWAInstallLib(lib)
env.DWAComponent(name, LIBS=[target], CPPPATH=incdir, COMPONENTS=components)
env.DWAInstallSConscriptStub(name, LIBS=target,
                             CPPPATH=[env.Dir('$INSTALL_DIR/include')],
                             COMPONENTS=components)
env.DWALinkValidate(name)
