import os
Import('env')

# ---------------------------------------------------------------

name = 'dso_discretizedisplayfilter'
target = 'DiscretizeDisplayFilter.so'
cc_source = ['DiscretizeDisplayFilter.cc']
ispc_source = ['DiscretizeDisplayFilter.ispc']
json_source = ['DiscretizeDisplayFilter.json']
components = [
    'rendering_displayfilter',
    'scene_rdl2'
]

# ---------------------------------------------------------------
()
env.DWAUseComponents(components)
dso = env.DWAIspcDso(env.File(target), cc_source, ispc_source, json_source)
env.DWAInstallIspcDso(dso)
