import os
Import('env')

# ---------------------------------------------------------------

name = 'dso_BlendDisplayFilter'
target = 'BlendDisplayFilter.so'
cc_source = ['BlendDisplayFilter.cc']
ispc_source = ['BlendDisplayFilter.ispc']
json_source = ['BlendDisplayFilter.json']
components = [
    'rendering_displayfilter',
    'scene_rdl2'
]

# ---------------------------------------------------------------
()
env.DWAUseComponents(components)
dso = env.DWAIspcDso(env.File(target), cc_source, ispc_source, json_source)
env.DWAInstallIspcDso(dso)
