Import('env')

# ---------------------------------------------------------------

target = 'TransformNormalMap.so'
cc_source = ['TransformNormalMap.cc']
ispc_source = ['TransformNormalMap.ispc']
json_source = ['TransformNormalMap.json']
components = [
    'shading_ispc',
    'rendering_shading',
    'scene_rdl2',
    'map_projection'
]

# ---------------------------------------------------------------

()
env.DWAUseComponents(components)
dso = env.DWAIspcDso(env.File(target), cc_source, ispc_source, json_source)
env.DWAInstallIspcDso(dso)
