import os
Import('env')

name = 'dso_dwalayermaterial'
target = 'DwaLayerMaterial.so'
cc_source = ['DwaLayerMaterial.cc']
ispc_source = ['DwaLayerMaterial.ispc']
json_source = ['DwaLayerMaterial.json']
components = [
    'render_util',
    'shading_ispc',
    'material_dwabase',
    'scene_rdl2',
    'material_glitter'
]

# --------------------------------------------------------------
env.DWAUseComponents(components)
dso = env.DWAIspcDso(env.File(target), cc_source, ispc_source, json_source)

env.DWAInstallIspcDso(dso)

baseDso = env.DWAComponent(
    name,
    COMPONENTS=components
)
env.AlwaysBuild(baseDso)

