import os
Import('env')

name = 'dso_dwatwosidedmaterial'
target = 'DwaTwoSidedMaterial.so'
cc_source = ['DwaTwoSidedMaterial.cc']
ispc_source = ['DwaTwoSidedMaterial.ispc']
json_source = ['DwaTwoSidedMaterial.json']
components = [
    'render_util',
    'rendering_pbr',
    'shading_ispc',
    'material_dwabase',
    'scene_rdl2'
]

# --------------------------------------------------------------
env.DWAUseComponents(components)
dso = env.DWAIspcDso(env.File(target), cc_source, ispc_source, json_source)

env.DWAInstallIspcDso(dso)

baseDso = env.DWAComponent(
    name,
    COMPONENTS=components
)
env.AlwaysBuild(baseDso)

