Import('env')

# ---------------------------------------------------------------

name = 'dso_lodmap'
target = 'LODMap.so'
cc_source = ['LODMap.cc']
ispc_source = ['LODMap.ispc']
json_source = ['LODMap.json']
components = [
    'shading_ispc',
    'scene_rdl2',
    'rendering_shading'
]

# ---------------------------------------------------------------
env.DWAUseComponents(components)
dso = env.DWAIspcDso(env.File(target), cc_source, ispc_source, json_source)
env.DWAInstallIspcDso(dso)
env.DWAComponent(name, COMPONENTS=components)
