Import('env')

# ---------------------------------------------------------------

target = 'HairColumnMap.so'
cc_source = ['HairColumnMap.cc']
ispc_source = ['HairColumnMap.ispc']
json_source = ['HairColumnMap.json']
components = [
    'shading_ispc',
    'rendering_shading',
    'scene_rdl2'
]

# ---------------------------------------------------------------

()
env.DWAUseComponents(components)
dso = env.DWAIspcDso(env.File(target), cc_source, ispc_source, json_source)
env.DWAInstallIspcDso(dso)
