import os
Import('env')

# ---------------------------------------------------------------

name = 'dso_convolutiondisplayfilter'
target = 'ConvolutionDisplayFilter.so'
cc_source = ['ConvolutionDisplayFilter.cc']
ispc_source = ['ConvolutionDisplayFilter.ispc']
json_source = ['ConvolutionDisplayFilter.json']
components = [
    'rendering_displayfilter',
    'scene_rdl2'
]

# ---------------------------------------------------------------
()
env.DWAUseComponents(components)
dso = env.DWAIspcDso(env.File(target), cc_source, ispc_source, json_source)
env.DWAInstallIspcDso(dso)
